### ISSUE TITLE
addPercentage or subtractPercentage only works for integers.

### ISSUE THREAD

**Issue by alcidesbsilvaneto** [ericelliott/moneysafe#36]
`$$($(100), subtractPercent(3.29)); // 97.00 when it should be 96.71`

**Comment by ericelliott** [comment]
Good catch! Want to submit a PR?

**Comment by alcidesbsilvaneto** [comment]
Sure, I'll work on it next weekend.

**Comment by ericelliott** [comment]
I can't reproduce this bug. The proposed tests already pass without the proposed code changes.
