### ISSUE TITLE
Support for fractions of cents

### ISSUE THREAD

**Issue by drewnoakes** [ericelliott/moneysafe#6]
Am I right in concluding this library only claims safety over hundredths of major units?

**Comment by drewnoakes** [comment]
Looking a little deeper I see some mention of 'cents per dollar'. Is this set across all values produced by the library, or can it be set per-value such that arithmetic on values of different bases works correctly?

Many of the financial values I work with are in fractions of cents. On platforms with richer type systems I'd use `decimal` or `BigDecimal`, where precision is part of the value.

**Comment by ericelliott** [comment]
MoneySafe operates at full IEEE floating point precision by default. It only rounds when you explicitly ask it to, by using the rounding lifts and methods.
